### ISSUE TITLE
Pattern follower ToDo list

### ISSUE THREAD

**Issue by IkerZamora** [IkerZamora/ros_erle_pattern_follower#1]
- [x] Suscribirse a la imagen y recibirla ([image_view](http://wiki.ros.org/image_view), [google](https://www.google.es/search?q=python+ros+image+susbcriber&oq=python+ros+image+susbcriber&aqs=chrome..69i57.4495j0j1&sourceid=chrome&es_sm=93&ie=UTF-8), [RosWiki](http://wiki.ros.org/rospy_tutorials/Tutorials/WritingImagePublisherSubscriber))
- [x] Extraer el patrón ([Google](https://www.google.es/search?q=artoolkit+pattern&biw=1008&bih=974&source=lnms&sa=X&sqi=2&pjf=1&ved=0ahUKEwjVhuSY7qHLAhUDDSwKHVVnDTIQ_AUICigA&dpr=1), [YouTube](https://www.youtube.com/watch?v=PiA4QRoSuxs), [ar_track_alvar](https://github.com/sniekum/ar_track_alvar), [waldo_example](http://machinelearningmastery.com/using-opencv-python-and-template-matching-to-play-wheres-waldo/))
- [x] Utilizar MavROS para sobreescribir el RC ( [ros_erle_teleoperation](https://github.com/erlerobot/ros_erle_teleoperation/tree/master/src/ROS), [ros_erle_computervision_teleoperation](https://github.com/erlerobot/ros_erle_computervision_teleoperation))

Others: 
- [hackster](https://www.hackster.io/LanderU/erle-brain-2-live-video-streaming-into-the-web-browser-b3733d?ref=platform&ref_id=12624_trending___&offset=9)
- [Instalation](http://dev.ardupilot.com/wiki/using-rosgazebo-simulator-with-sitl/)

**Comment by IkerZamora** [comment]
This can be used to create the model from a tag:
https://github.com/keulYSMB/gazebo_models

**Comment by IkerZamora** [comment]
How to install ARToolkit http://www.cursosrobolab.com/tutoriales/compilacion-e-instalacion-de-artoolkit-para-sistemas-basados-en-debian-ubuntu/
